spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      format_sql: false
      show-sql: false
      generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  h2:
    console:
      enabled:
        debug: true
lib:
   bookcount: 50
   authorcount: 4
   maxamount: 50000
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,startup,shutdown
  info:
    env:
      enabled: true
info:
  app:
    name: Archana Sweets
    description: | 
      A Spring Boot app that provides a Web UI developed through Thymeleaf Template Resolver and REST end points through Spring REST.
      It used Spring JPA to connect to the databases. There are three database options to choose from, H2 and MySQL. 
      You should be able to switch between in-memmory and persistant H2 data stores by changing the active profile in the application.yml file. 
      This application will expose the H2 Console through http://localhost:8082/h2-console/ and the swagger documenation through http://localhost:8082/swagger-ui.html
    version: 2.0.0