services:
  apis:
    image: "vjponnusamy/my-farm-apis:20240203"
    container_name: farms_api_container
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - dhariyafarms
  clients:
    image: "vjponnusamy/my-farm-clients:20240203"
    container_name: farms_clients_container
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - dhariyafarms
networks:
  dhariyafarms:
    driver: "bridge"